language: ruby
rvm:
- 2.2.3
notifications:
  slack:
    secure: DL4KstH3WueJvIJeLx2xKgRp1M/d1GLnRTGvBgaPWHilxREbq7MtRcnDl5YViNTIephDleYuVljeZvXYU/qftcSZi5Mjdw06E3FQXRJ9AJxPlT8de055S0e8jWvIQikjriZSvrYz5bBxQkU/VMHvu9j6YbX91soChG1zyV4Fr40WK7JLuj1xohoLCulhWXF1eCPjsyX7rMB9G0HNGDX7UH9wnTPp65UyWL/LP3KkLdgeIbWQMpS9P4cPj40zSrsITjaEgEaTKCLVsREJDf0sx+6QzGfkG1/RKyoVyKbXl67Y/f1EUSfxAlwdkHSA7dHPHvM1MClC7FULFazr1efCLhXobruxxpLyiv19OD2NMgQqU+lOtynl19ec3CUjhNIgInOTG0qOiXQdCBQmyN5FEqYYE3m21+1v4AUGVr6c46ROK97cCpylLI3U5z2xXE3MBKwMTqIwLPGB/Gccv3pVRsgvAmQ7u+44JsvuDRcrwnu/8BGEjSsZdoNxJRfrkCgM/5eD9v9RAkYdGkkK7jXVlFv6eXl6NgZTm5q+zP551hdcDnsOZ78Sl9tnS4Q74DR17Np1c7e9Fpn+ylox/zNR3xh50e52Nlu9PsvjkGS+wFOg/cG4JFPKCRVtCUh1KR/Y4kvGG8ILBFHGKJ6cYmabEp3vmnb73HIRDKq1+Y2/6tU=
